# Generated by Django 2.0.2 on 2018-03-06 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='date_of_birth',
            new_name='birth_date',
        ),
    ]
