# Generated by Django 2.0.2 on 2018-03-09 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0008_patient_urine_output'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='urine_output',
        ),
    ]
