# Generated by Django 2.0.2 on 2018-03-09 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0009_remove_patient_urine_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='urine_output',
            field=models.CharField(choices=[(1, 'Normal'), (2, 'Reduced urine output'), (3, 'Not passed urine for 12-18 hours'), (4, 'Not passed urine for over 18 hours')], default=1, max_length=2),
        ),
    ]
