# Generated by Django 2.0.2 on 2018-03-10 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0012_auto_20180310_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.AlterField(
            model_name='patient',
            name='urine_output',
            field=models.CharField(max_length=2),
        ),
    ]
