# Generated by Django 2.0.2 on 2018-03-10 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0019_auto_20180310_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='nhs_no',
            field=models.BigIntegerField(),
        ),
    ]
