# Generated by Django 2.0.3 on 2018-03-14 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0020_auto_20180310_2052'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='blood_pressure',
            new_name='sys_blood_pressure',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='nhs_no',
        ),
    ]
