# Generated by Django 2.0.2 on 2018-03-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField()),
                ('nhs_no', models.IntegerField()),
                ('temp', models.DecimalField(decimal_places=2, max_digits=4)),
                ('pulse', models.DecimalField(decimal_places=2, max_digits=4)),
                ('resp_rate', models.DecimalField(decimal_places=2, max_digits=4)),
                ('blood_pressure', models.DecimalField(decimal_places=2, max_digits=4)),
                ('cap_refill_time', models.DecimalField(decimal_places=2, max_digits=4)),
                ('o2_stats', models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
    ]
