# Generated by Django 2.0.2 on 2018-03-10 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sepsisrisk', '0010_patient_urine_output'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='urine_output',
            field=models.TextField(),
        ),
    ]
